"""
API models package.

This package contains request and response models for FastAPI endpoints.
"""

# Import all request models
from app.models.api.requests import (
    CampaignInstanceCreateRequest,
    CampaignInstanceUpdateRequest,
    CampaignTemplateCreateRequest,
    CampaignTemplateUpdateRequest,
    CharacterTemplateCreateRequest,
    CharacterTemplateUpdateRequest,
    ContentPackCreateRequest,
    ContentPackUpdateRequest,
    ContentUploadItem,
    ContentUploadRequest,
    CreateCampaignFromTemplateRequest,
    LoadGameRequest,
    PerformRollRequest,
    PlayerActionRequest,
    SubmitRollsRequest,
)

# Import all response models
from app.models.api.responses import (
    AdventureCharacterData,
    AdventureInfo,
    CharacterAdventuresResponse,
    CharacterCreationOptionsData,
    CharacterCreationOptionsMetadata,
    CharacterCreationOptionsResponse,
    ConfigData,
    ConfigResponse,
    ContentItem,
    ContentListResponse,
    ContentPackItemsResponse,
    ContentPackStatistics,
    ContentPackWithStatisticsResponse,
    ContentUploadResponse,
    ContentUploadResult,
    CreateCampaignFromTemplateResponse,
    DiceRollResponse,
    GameEventResponseModel,
    ListResponse,
    LoadGameResponse,
    SaveGameResponse,
    SSEConnectionResponse,
    SSEHealthResponse,
    StartCampaignResponse,
    SuccessResponse,
    SupportedContentTypesResponse,
)

__all__ = [
    # Request models
    "CampaignInstanceCreateRequest",
    "CampaignInstanceUpdateRequest",
    "CampaignTemplateCreateRequest",
    "CampaignTemplateUpdateRequest",
    "CharacterTemplateCreateRequest",
    "CharacterTemplateUpdateRequest",
    "ContentPackCreateRequest",
    "ContentPackUpdateRequest",
    "ContentUploadItem",
    "ContentUploadRequest",
    "CreateCampaignFromTemplateRequest",
    "LoadGameRequest",
    "PerformRollRequest",
    "PlayerActionRequest",
    "SubmitRollsRequest",
    # Response models
    "AdventureCharacterData",
    "AdventureInfo",
    "CharacterAdventuresResponse",
    "CharacterCreationOptionsData",
    "CharacterCreationOptionsMetadata",
    "CharacterCreationOptionsResponse",
    "ConfigData",
    "ConfigResponse",
    "ContentItem",
    "ContentListResponse",
    "ContentPackItemsResponse",
    "ContentPackStatistics",
    "ContentPackWithStatisticsResponse",
    "ContentUploadResponse",
    "ContentUploadResult",
    "CreateCampaignFromTemplateResponse",
    "DiceRollResponse",
    "GameEventResponseModel",
    "ListResponse",
    "LoadGameResponse",
    "SaveGameResponse",
    "SSEConnectionResponse",
    "SSEHealthResponse",
    "StartCampaignResponse",
    "SuccessResponse",
    "SupportedContentTypesResponse",
]
