"""
Pattern dictionaries for RAG query engine.

This module contains all the keyword patterns used by the query engine
to identify different types of player actions and generate appropriate queries.
"""

from typing import Set

# Spell-related patterns
SPELL_PATTERNS: Set[str] = {
    "cast",
    "casting",
    "spell",
    "cantrip",
    "ritual",
    "fireball",
    "magic missile",
    "shield",
    "cure wounds",
    "healing word",
    "thunderwave",
    "burning hands",
    "mage armor",
    "detect magic",
    "identify",
    "sleep",
    "charm person",
    "disguise self",
    "silent image",
    "misty step",
    "scorching ray",
    "web",
    "counterspell",
    "fly",
    "haste",
    "slow",
    "dimension door",
    "polymorph",
    "wall of fire",
}

# Skill-related patterns
SKILL_PATTERNS: Set[str] = {
    "stealth",
    "sneak",
    "hide",
    "hidden",
    "persuade",
    "persuasion",
    "convince",
    "negotiate",
    "intimidate",
    "intimidation",
    "threaten",
    "scare",
    "deception",
    "deceive",
    "lie",
    "bluff",
    "athletics",
    "climb",
    "jump",
    "swim",
    "acrobatics",
    "balance",
    "tumble",
    "perception",
    "notice",
    "spot",
    "see",
    "look",
    "investigation",
    "investigate",
    "search",
    "examine",
    "insight",
    "sense motive",
    "read",
    "survival",
    "track",
    "forage",
    "medicine",
    "heal",
    "treat",
    "history",
    "recall",
    "remember",
    "arcana",
    "magical knowledge",
    "nature",
    "natural",
    "religion",
    "religious",
}

# Combat-related patterns
COMBAT_PATTERNS: Set[str] = {
    "attack",
    "strike",
    "hit",
    "slash",
    "stab",
    "shoot",
    "fire",
    "defend",
    "parry",
    "dodge",
    "block",
    "evade",
    "damage",
    "hurt",
    "wound",
    "kill",
    "defeat",
}

# Equipment and item patterns
EQUIPMENT_PATTERNS: Set[str] = {
    # Weapons
    "sword",
    "shortsword",
    "longsword",
    "greatsword",
    "axe",
    "greataxe",
    "handaxe",
    "battleaxe",
    "mace",
    "spear",
    "dagger",
    "bow",
    "longbow",
    "shortbow",
    "crossbow",
    "staff",
    "quarterstaff",
    "hammer",
    "warhammer",
    "club",
    "rapier",
    "scimitar",
    "weapon",
    "weapons",
    # Armor
    "armor",
    "armour",
    "shield",
    "helm",
    "helmet",
    "breastplate",
    "chainmail",
    "leather",
    "plate",
    # General items
    "rope",
    "torch",
    "lantern",
    "backpack",
    "potion",
    "scroll",
    "equipment",
    "gear",
    "item",
    "items",
    # Shopping terms
    "buy",
    "purchase",
    "shop",
    "store",
    "merchant",
    "cost",
    "price",
    "gold",
    "silver",
    "copper",
}

# Social interaction patterns
SOCIAL_PATTERNS: Set[str] = {
    "talk",
    "speak",
    "say",
    "ask",
    "tell",
    "converse",
    "greet",
    "introduce",
    "discuss",
    "negotiate",
    "barter",
}

# Exploration patterns
EXPLORATION_PATTERNS: Set[str] = {
    "explore",
    "go",
    "move",
    "travel",
    "enter",
    "exit",
    "open",
    "close",
    "unlock",
    "lock",
    "door",
    "gate",
    "room",
    "corridor",
    "hallway",
    "chamber",
}

# Location query patterns
LOCATION_PATTERNS: Set[str] = {
    "where",
    "location",
    "place",
    "city",
    "town",
    "village",
    "kingdom",
    "realm",
    "region",
    "area",
    "district",
}

# Creature/monster patterns
CREATURE_PATTERNS: Set[str] = {
    "goblin",
    "orc",
    "dragon",
    "skeleton",
    "zombie",
    "wolf",
    "bear",
    "ogre",
    "troll",
    "giant",
    "kobold",
    "gnoll",
    "bugbear",
    "hobgoblin",
    "lich",
    "vampire",
    "werewolf",
    "demon",
    "devil",
    "elemental",
    "beholder",
    "mind flayer",
    "illithid",
    "drow",
    "elf",
    "dwarf",
    "bandit",
    "guard",
    "cultist",
    "mage",
    "wizard",
    "warrior",
    "spider",
    "rat",
    "bat",
    "snake",
    "boar",
    "lion",
    "tiger",
    "wyvern",
    "drake",
    "hydra",
    "basilisk",
    "cockatrice",
    "griffon",
    "minotaur",
    "centaur",
    "harpy",
    "medusa",
    "gorgon",
    "chimera",
    "ghoul",
    "wight",
    "wraith",
    "specter",
    "ghost",
    "banshee",
    "golem",
    "construct",
    "animated",
    "ooze",
    "slime",
    "gelatinous cube",
}

# Class and subclass patterns
CLASS_PATTERNS: Set[str] = {
    "fighter",
    "wizard",
    "cleric",
    "rogue",
    "ranger",
    "paladin",
    "barbarian",
    "bard",
    "druid",
    "monk",
    "sorcerer",
    "warlock",
    "artificer",
    "class",
    "classes",
    "subclass",
    "subclasses",
    "archetype",
    "school",
    "tradition",
    "college",
    "domain",
    "oath",
    "pact",
    "path",
    "level",
    "levels",
    "level up",
    "leveling",
    "multiclass",
    "multiclassing",
    "ability score",
    "improvement",
    "feat",
    "feats",
    "feature",
    "features",
    "hit dice",
    "hit die",
}

# Race and subrace patterns
RACE_PATTERNS: Set[str] = {
    "human",
    "humans",
    "elf",
    "elves",
    "dwarf",
    "dwarves",
    "halfling",
    "halflings",
    "gnome",
    "gnomes",
    "half-elf",
    "half-elves",
    "half-orc",
    "half-orcs",
    "tiefling",
    "tieflings",
    "dragonborn",
    "race",
    "races",
    "subrace",
    "subraces",
    "variant",
    "ancestry",
    "heritage",
    "lineage",
    "high elf",
    "high elves",
    "wood elf",
    "wood elves",
    "dark elf",
    "dark elves",
    "drow",
    "mountain dwarf",
    "mountain dwarves",
    "hill dwarf",
    "hill dwarves",
    "lightfoot",
    "stout",
    "rock gnome",
    "rock gnomes",
    "forest gnome",
    "traits",
    "racial",
    "darkvision",
    "speed",
    "size",
}
