"""Add vector embedding columns

Revision ID: 2032c7f301f0
Revises: 2a409eb9e9d3
Create Date: 2025-06-12 13:54:39.985893

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.database.models import VECTOR

# revision identifiers, used by Alembic.
revision: str = "2032c7f301f0"
down_revision: Union[str, None] = "2a409eb9e9d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ability_scores", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("alignments", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("backgrounds", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("classes", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("conditions", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("damage_types", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("equipment", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column(
        "equipment_categories", sa.Column("embedding", VECTOR(384), nullable=True)
    )
    op.add_column("feats", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("features", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("languages", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("levels", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("magic_items", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("magic_schools", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("monsters", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("proficiencies", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("races", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("rule_sections", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("rules", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("skills", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("spells", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("subclasses", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("subraces", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column("traits", sa.Column("embedding", VECTOR(384), nullable=True))
    op.add_column(
        "weapon_properties", sa.Column("embedding", VECTOR(384), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weapon_properties", "embedding")
    op.drop_column("traits", "embedding")
    op.drop_column("subraces", "embedding")
    op.drop_column("subclasses", "embedding")
    op.drop_column("spells", "embedding")
    op.drop_column("skills", "embedding")
    op.drop_column("rules", "embedding")
    op.drop_column("rule_sections", "embedding")
    op.drop_column("races", "embedding")
    op.drop_column("proficiencies", "embedding")
    op.drop_column("monsters", "embedding")
    op.drop_column("magic_schools", "embedding")
    op.drop_column("magic_items", "embedding")
    op.drop_column("levels", "embedding")
    op.drop_column("languages", "embedding")
    op.drop_column("features", "embedding")
    op.drop_column("feats", "embedding")
    op.drop_column("equipment_categories", "embedding")
    op.drop_column("equipment", "embedding")
    op.drop_column("damage_types", "embedding")
    op.drop_column("conditions", "embedding")
    op.drop_column("classes", "embedding")
    op.drop_column("backgrounds", "embedding")
    op.drop_column("alignments", "embedding")
    op.drop_column("ability_scores", "embedding")
    # ### end Alembic commands ###
