"""Initial migration with D5e content tables

Revision ID: 2a409eb9e9d3
Revises:
Create Date: 2025-06-11 21:08:37.318066

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a409eb9e9d3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_packs",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ability_scores",
        sa.Column("full_name", sa.String(length=20), nullable=True),
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "alignments",
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("abbreviation", sa.String(length=2), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "backgrounds",
        sa.Column("starting_proficiencies", sa.JSON(), nullable=True),
        sa.Column("starting_equipment", sa.JSON(), nullable=True),
        sa.Column("starting_equipment_options", sa.JSON(), nullable=True),
        sa.Column("language_options", sa.JSON(), nullable=True),
        sa.Column("feature", sa.JSON(), nullable=True),
        sa.Column("personality_traits", sa.JSON(), nullable=True),
        sa.Column("ideals", sa.JSON(), nullable=True),
        sa.Column("bonds", sa.JSON(), nullable=True),
        sa.Column("flaws", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "classes",
        sa.Column("hit_die", sa.Integer(), nullable=False),
        sa.Column("proficiencies", sa.JSON(), nullable=True),
        sa.Column("proficiency_choices", sa.JSON(), nullable=True),
        sa.Column("saving_throws", sa.JSON(), nullable=True),
        sa.Column("starting_equipment", sa.JSON(), nullable=True),
        sa.Column("starting_equipment_options", sa.JSON(), nullable=True),
        sa.Column("class_levels", sa.String(length=200), nullable=True),
        sa.Column("multi_classing", sa.JSON(), nullable=True),
        sa.Column("subclasses", sa.JSON(), nullable=True),
        sa.Column("spellcasting", sa.JSON(), nullable=True),
        sa.Column("spells", sa.String(length=200), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "conditions",
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "damage_types",
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "equipment",
        sa.Column("equipment_category", sa.JSON(), nullable=True),
        sa.Column("weapon_category", sa.String(length=50), nullable=True),
        sa.Column("weapon_range", sa.String(length=20), nullable=True),
        sa.Column("category_range", sa.String(length=100), nullable=True),
        sa.Column("cost", sa.JSON(), nullable=True),
        sa.Column("damage", sa.JSON(), nullable=True),
        sa.Column("range", sa.JSON(), nullable=True),
        sa.Column("weight", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("armor_category", sa.String(length=50), nullable=True),
        sa.Column("armor_class", sa.JSON(), nullable=True),
        sa.Column("str_minimum", sa.Integer(), nullable=True),
        sa.Column("stealth_disadvantage", sa.Boolean(), nullable=True),
        sa.Column("tool_category", sa.String(length=50), nullable=True),
        sa.Column("vehicle_category", sa.String(length=50), nullable=True),
        sa.Column("speed", sa.JSON(), nullable=True),
        sa.Column("capacity", sa.String(length=50), nullable=True),
        sa.Column("gear_category", sa.JSON(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "equipment_categories",
        sa.Column("equipment", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "feats",
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("prerequisites", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "features",
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("class_ref", sa.JSON(), nullable=True),
        sa.Column("subclass", sa.JSON(), nullable=True),
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("parent", sa.JSON(), nullable=True),
        sa.Column("prerequisites", sa.JSON(), nullable=True),
        sa.Column("feature_specific", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "languages",
        sa.Column("type", sa.String(length=20), nullable=True),
        sa.Column("typical_speakers", sa.JSON(), nullable=True),
        sa.Column("script", sa.String(length=50), nullable=True),
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "levels",
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("class_ref", sa.JSON(), nullable=True),
        sa.Column("subclass", sa.JSON(), nullable=True),
        sa.Column("ability_score_bonuses", sa.Integer(), nullable=True),
        sa.Column("prof_bonus", sa.Integer(), nullable=True),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("spellcasting", sa.JSON(), nullable=True),
        sa.Column("class_specific", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "magic_items",
        sa.Column("equipment_category", sa.JSON(), nullable=True),
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("rarity", sa.JSON(), nullable=True),
        sa.Column("variants", sa.JSON(), nullable=True),
        sa.Column("variant", sa.Boolean(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "magic_schools",
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "monsters",
        sa.Column("size", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("subtype", sa.String(length=50), nullable=True),
        sa.Column("alignment", sa.String(length=50), nullable=True),
        sa.Column("armor_class", sa.JSON(), nullable=True),
        sa.Column("hit_points", sa.Integer(), nullable=False),
        sa.Column("hit_dice", sa.String(length=20), nullable=True),
        sa.Column("hit_points_roll", sa.String(length=50), nullable=True),
        sa.Column("speed", sa.JSON(), nullable=True),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("dexterity", sa.Integer(), nullable=False),
        sa.Column("constitution", sa.Integer(), nullable=False),
        sa.Column("intelligence", sa.Integer(), nullable=False),
        sa.Column("wisdom", sa.Integer(), nullable=False),
        sa.Column("charisma", sa.Integer(), nullable=False),
        sa.Column("proficiencies", sa.JSON(), nullable=True),
        sa.Column("damage_vulnerabilities", sa.JSON(), nullable=True),
        sa.Column("damage_resistances", sa.JSON(), nullable=True),
        sa.Column("damage_immunities", sa.JSON(), nullable=True),
        sa.Column("condition_immunities", sa.JSON(), nullable=True),
        sa.Column("senses", sa.JSON(), nullable=True),
        sa.Column("languages", sa.Text(), nullable=True),
        sa.Column("challenge_rating", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("proficiency_bonus", sa.Integer(), nullable=True),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("special_abilities", sa.JSON(), nullable=True),
        sa.Column("actions", sa.JSON(), nullable=True),
        sa.Column("legendary_actions", sa.JSON(), nullable=True),
        sa.Column("reactions", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "proficiencies",
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("classes", sa.JSON(), nullable=True),
        sa.Column("races", sa.JSON(), nullable=True),
        sa.Column("references", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "races",
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.Column("ability_bonuses", sa.JSON(), nullable=True),
        sa.Column("ability_bonus_options", sa.JSON(), nullable=True),
        sa.Column("alignment", sa.Text(), nullable=True),
        sa.Column("age", sa.Text(), nullable=True),
        sa.Column("size", sa.String(length=20), nullable=True),
        sa.Column("size_description", sa.Text(), nullable=True),
        sa.Column("starting_proficiencies", sa.JSON(), nullable=True),
        sa.Column("starting_proficiency_options", sa.JSON(), nullable=True),
        sa.Column("languages", sa.JSON(), nullable=True),
        sa.Column("language_options", sa.JSON(), nullable=True),
        sa.Column("language_desc", sa.Text(), nullable=True),
        sa.Column("traits", sa.JSON(), nullable=True),
        sa.Column("subraces", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "rule_sections",
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "rules",
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("subsections", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "skills",
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("ability_score", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "spells",
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("higher_level", sa.JSON(), nullable=True),
        sa.Column("range", sa.String(length=50), nullable=True),
        sa.Column("components", sa.JSON(), nullable=True),
        sa.Column("material", sa.Text(), nullable=True),
        sa.Column("ritual", sa.Boolean(), nullable=True),
        sa.Column("duration", sa.String(length=100), nullable=True),
        sa.Column("concentration", sa.Boolean(), nullable=True),
        sa.Column("casting_time", sa.String(length=100), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("attack_type", sa.String(length=20), nullable=True),
        sa.Column("damage", sa.JSON(), nullable=True),
        sa.Column("school", sa.JSON(), nullable=True),
        sa.Column("classes", sa.JSON(), nullable=True),
        sa.Column("subclasses", sa.JSON(), nullable=True),
        sa.Column("dc", sa.JSON(), nullable=True),
        sa.Column("area_of_effect", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "subclasses",
        sa.Column("class_ref", sa.JSON(), nullable=True),
        sa.Column("subclass_flavor", sa.Text(), nullable=True),
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("subclass_levels", sa.String(length=200), nullable=True),
        sa.Column("spells", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "subraces",
        sa.Column("race", sa.JSON(), nullable=True),
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("ability_bonuses", sa.JSON(), nullable=True),
        sa.Column("starting_proficiencies", sa.JSON(), nullable=True),
        sa.Column("languages", sa.JSON(), nullable=True),
        sa.Column("language_options", sa.JSON(), nullable=True),
        sa.Column("racial_traits", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "traits",
        sa.Column("races", sa.JSON(), nullable=True),
        sa.Column("subraces", sa.JSON(), nullable=True),
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("proficiencies", sa.JSON(), nullable=True),
        sa.Column("proficiency_choices", sa.JSON(), nullable=True),
        sa.Column("language_options", sa.JSON(), nullable=True),
        sa.Column("trait_specific", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    op.create_table(
        "weapon_properties",
        sa.Column("desc", sa.JSON(), nullable=True),
        sa.Column("index", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("content_pack_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_pack_id"],
            ["content_packs.id"],
        ),
        sa.PrimaryKeyConstraint("index"),
        sa.UniqueConstraint("index", "content_pack_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weapon_properties")
    op.drop_table("traits")
    op.drop_table("subraces")
    op.drop_table("subclasses")
    op.drop_table("spells")
    op.drop_table("skills")
    op.drop_table("rules")
    op.drop_table("rule_sections")
    op.drop_table("races")
    op.drop_table("proficiencies")
    op.drop_table("monsters")
    op.drop_table("magic_schools")
    op.drop_table("magic_items")
    op.drop_table("levels")
    op.drop_table("languages")
    op.drop_table("features")
    op.drop_table("feats")
    op.drop_table("equipment_categories")
    op.drop_table("equipment")
    op.drop_table("damage_types")
    op.drop_table("conditions")
    op.drop_table("classes")
    op.drop_table("backgrounds")
    op.drop_table("alignments")
    op.drop_table("ability_scores")
    op.drop_table("content_packs")
    # ### end Alembic commands ###
